name: Nightly build

on:
  push:
    branches:
      - "cicd"
    paths-ignore:
      #- ".github/**"
      - "*.md"

env:
  EXEGOL_VERSION:

jobs:
  build-n-publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python -m pip install build wheel --user
      - name: Run unitest
        run : python setup.py clean test
      - name: Generate build number
        id: prepare_build
        run: |
          COMMIT_ID=$(git rev-parse "$GITHUB_SHA")
          WRAPPER_VERSION=${COMMIT_ID:0:8}
          echo "wrapper_version=${WRAPPER_VERSION}" >> $GITHUB_OUTPUT
      - name: Build Exegol
        env:
          EXEGOL_VERSION: ${{ steps.prepare_build.outputs.wrapper_version }}
        run: python -m build --sdist --outdir dist/ .
      - name: Publish distribution ðŸ“¦ to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
